### ISSUE TITLE
Fix AUR package

### ISSUE THREAD

**Issue by schrmh** [jle64/nautilus-search-by-image#2]
```
Cloning into bare repository '/home/duda/PKGBUILDs/nautilus-search-by-image-git/nautilus-search-by-image'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out

==> ERROR: Failure while downloading nautilus-search-by-image git repo
    Aborting...
==> ERROR: Could not download sources.

```

**Comment by jle64** [comment]
Thanks for reporting the issue,

I've disowned the package on aur as I've no current motivation to look into it.

This makes it possible for anyone to take ownership and fix it, if they can be bothered.

Github has deprecated the git protocol, so the URL just needs to be changed i guess.

**Comment by schrmh** [comment]
Yep, for anyone reading here you can check out https://aur.archlinux.org/cgit/aur.git/commit/?h=linux-zen-git&id=9aa33eedcc2ccad908b7972df4a176b64924f53f to see how a (I think) pretty popular package handled this.

GitHub deprecated git:// as jle64 mentioned. You can read about here: https://stackoverflow.com/questions/72915782/fatal-unable-to-connect-to-github-com-github-com0-140-82-121-3-errno-opera

For nautilus-search-by-image it works with that patch (adding +https between git and ://):
```
14c14
< source=('nautilus-search-by-image::git+https://github.com/jle64/nautilus-search-by-image.git')
---
> source=('nautilus-search-by-image::git://github.com/jle64/nautilus-search-by-image.git')
```
